name: Build and publish

on: 
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_SEARCH_KEY: ${{secrets.TYPESENSE_SEARCH_KEY}}
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
      TYPESENSE_HOST: ${{secrets.TYPESENSE_HOST}}
      TYPESENSE_PORT: ${{vars.TYPESENSE_PORT}}
      TYPESENSE_PROTOCOL: ${{vars.TYPESENSE_PROTOCOL}}
      RETRIEVED_TEXTS_DIR: ./data/externally_sourced_texts/
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: fetch data
      run: | 
        ./shellscripts/fetch_editions.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: fetched fresh data from gh-data repo
    - name: copy basic texts for pages
      run: |
        if [ -d $RETRIEVED_TEXTS_DIR ]; then rm -rf $RETRIEVED_TEXTS_DIR; fi
        mkdir $RETRIEVED_TEXTS_DIR
        wget https://github.com/bundesverfassung-oesterreich/bv-commentary-parser/raw/main/tei/about_bvg.xml -P $RETRIEVED_TEXTS_DIR
        wget https://raw.githubusercontent.com/bundesverfassung-oesterreich/bv-commentary-parser/main/tei/about_project.xml -P $RETRIEVED_TEXTS_DIR
        wget https://raw.githubusercontent.com/bundesverfassung-oesterreich/bv-commentary-parser/main/tei/index.xml -P $RETRIEVED_TEXTS_DIR
    - name: Install Saxon, Ant and Python
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./shellscripts/script.sh
        pip install -r ./pyscripts/requirements.txt
    - name: Build
      run: |
        ant
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html
    - name: Setup Typesense
      run: |
        python ./pyscripts/setup_typesense.py
