name: Build and publish

on: 
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_SEARCH_KEY: ${{secrets.TYPESENSE_SEARCH_KEY}}
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
      TYPESENSE_HOST: ${{secrets.TYPESENSE_HOST}}
      TYPESENSE_PORT: ${{vars.TYPESENSE_PORT}}
      TYPESENSE_PROTOCOL: ${{vars.TYPESENSE_PROTOCOL}}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: fetch data
      run: | 
        ./shellscripts/fetch_editions.sh
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: fetched fresh data from gh-data repo
    - name: copy basic texts for pages
      run: |
        ./shellscripts/fetch_docx_texts.sh
    - name: Install Saxon, Ant and Python
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./shellscripts/script.sh
        pip install -r ./pyscripts/requirements.txt
    - name: imprint
      run: |
        ./shellscripts/dl_imprint.sh
    - name: Build
      run: |
        ant
    - name: xml documentation page
      run: |
        python pyscripts/build_xml_docupage.py
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./html"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Setup Typesense
      run: |
        python ./pyscripts/setup_typesense.py