name: Build and publish

on: 
  push:
  workflow_dispatch:

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_SEARCH_KEY: ${{secrets.TYPESENSE_SEARCH_KEY}}
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
      TYPESENSE_HOST: ${{secrets.TYPESENSE_HOST}}
      TYPESENSE_PORT: ${{vars.TYPESENSE_PORT}}
      TYPESENSE_PROTOCOL: ${{vars.TYPESENSE_PROTOCOL}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: Install Saxon, Ant and Python
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./shellscripts/script.sh
        pip install -r ./pyscripts/requirements.txt
    - name: fetch data
      run: | 
        ./shellscripts/fetch_editions.sh
    - name: add navigation anchors
      run: |
        ./shellscripts/add_navigation_layer.sh
    - name: Build
      run: |
        ant
    - name: Update Favicons
      run: python ./pyscripts/update_favicons.py
    - name: Update Translations
      run: python ./pyscripts/make_translations.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html
    - name: Setup Typesense
      run: |
        python ./pyscripts/setup_typesense.py
